
package com.mohsinkd786.java.ws.soap.api;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductServiceImpl", targetNamespace = "http://api.soap.ws.java.mohsinkd786.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.mohsinkd786.java.ws.soap.api.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductById", targetNamespace = "http://api.soap.ws.java.mohsinkd786.com/", className = "com.mohsinkd786.java.ws.soap.api.GetProductById")
    @ResponseWrapper(localName = "getProductByIdResponse", targetNamespace = "http://api.soap.ws.java.mohsinkd786.com/", className = "com.mohsinkd786.java.ws.soap.api.GetProductByIdResponse")
    @Action(input = "http://api.soap.ws.java.mohsinkd786.com/ProductServiceImpl/getProductByIdRequest", output = "http://api.soap.ws.java.mohsinkd786.com/ProductServiceImpl/getProductByIdResponse")
    public Product getProductById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.mohsinkd786.java.ws.soap.api.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://api.soap.ws.java.mohsinkd786.com/", className = "com.mohsinkd786.java.ws.soap.api.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://api.soap.ws.java.mohsinkd786.com/", className = "com.mohsinkd786.java.ws.soap.api.GetAllProductsResponse")
    @Action(input = "http://api.soap.ws.java.mohsinkd786.com/ProductServiceImpl/getAllProductsRequest", output = "http://api.soap.ws.java.mohsinkd786.com/ProductServiceImpl/getAllProductsResponse")
    public List<Product> getAllProducts();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://api.soap.ws.java.mohsinkd786.com/", className = "com.mohsinkd786.java.ws.soap.api.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://api.soap.ws.java.mohsinkd786.com/", className = "com.mohsinkd786.java.ws.soap.api.AddProductResponse")
    @Action(input = "http://api.soap.ws.java.mohsinkd786.com/ProductServiceImpl/addProductRequest", output = "http://api.soap.ws.java.mohsinkd786.com/ProductServiceImpl/addProductResponse")
    public void addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

}
